# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               GHS Seafarer
tagline:             ''
description:         'Teragion's personal blog'
url:                 https://teragion.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Zeyuan He
  url:               https://teragion.github.io
  email:             assancious@gmail.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
