# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:                阿青的博客
tagline:             '这是注释，耶！'
description:         'descriptions will... ehh... somehow, be added'
url:                 https://teragion.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Zeyuan He
  url:               https://teragion.github.io
  email:             assancious@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/Teragion/teragion.github.io

# Plugins
plugins:
  - jekyll-paginate

markdown: kramdown
