# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:                GHS Seafarer
tagline:             'Good Luck and Fair Seas'
description:         'descriptions will... ehh... somehow, be added'
url:                 http://teragion.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Zeyuan He
  url:               https://teragion.github.io
  email:             assancious@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/Teragion/teragion.github.io

# Plugins
plugins:
  - jekyll-paginate
